 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.server.register;
import protocol.msgId.Id;
public class ServerRegisterIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(protocol.server.register.ServerRegister.MSG_REQ_Server_Register.class, 0xFF0001);
          Id.getInst().SetMessage(protocol.server.register.ServerRegister.MSG_RES_Server_Register.class, 0xFF0002);
          Id.getInst().SetMessage(protocol.server.register.ServerRegister.ConnectInfo.class, 0xFF0003);
     }
}
