// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerRegister.proto

package protocol.server.register;

public final class ServerRegister {
  private ServerRegister() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MSG_REQ_Server_RegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.server.register.MSG_REQ_Server_Register)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 serverType = 1;</code>
     */
    boolean hasServerType();
    /**
     * <code>required int32 serverType = 1;</code>
     */
    int getServerType();

    /**
     * <code>optional int32 groupId = 2;</code>
     */
    boolean hasGroupId();
    /**
     * <code>optional int32 groupId = 2;</code>
     */
    int getGroupId();

    /**
     * <code>optional int32 subId = 3;</code>
     */
    boolean hasSubId();
    /**
     * <code>optional int32 subId = 3;</code>
     */
    int getSubId();
  }
  /**
   * Protobuf type {@code protocol.server.register.MSG_REQ_Server_Register}
   */
  public  static final class MSG_REQ_Server_Register extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.server.register.MSG_REQ_Server_Register)
      MSG_REQ_Server_RegisterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MSG_REQ_Server_Register.newBuilder() to construct.
    private MSG_REQ_Server_Register(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MSG_REQ_Server_Register() {
      serverType_ = 0;
      groupId_ = 0;
      subId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_REQ_Server_Register(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              groupId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              subId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_REQ_Server_Register_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_REQ_Server_Register_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.server.register.ServerRegister.MSG_REQ_Server_Register.class, protocol.server.register.ServerRegister.MSG_REQ_Server_Register.Builder.class);
    }

    private int bitField0_;
    public static final int SERVERTYPE_FIELD_NUMBER = 1;
    private int serverType_;
    /**
     * <code>required int32 serverType = 1;</code>
     */
    public boolean hasServerType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 serverType = 1;</code>
     */
    public int getServerType() {
      return serverType_;
    }

    public static final int GROUPID_FIELD_NUMBER = 2;
    private int groupId_;
    /**
     * <code>optional int32 groupId = 2;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 groupId = 2;</code>
     */
    public int getGroupId() {
      return groupId_;
    }

    public static final int SUBID_FIELD_NUMBER = 3;
    private int subId_;
    /**
     * <code>optional int32 subId = 3;</code>
     */
    public boolean hasSubId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 subId = 3;</code>
     */
    public int getSubId() {
      return subId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, groupId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, subId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, groupId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, subId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.server.register.ServerRegister.MSG_REQ_Server_Register)) {
        return super.equals(obj);
      }
      protocol.server.register.ServerRegister.MSG_REQ_Server_Register other = (protocol.server.register.ServerRegister.MSG_REQ_Server_Register) obj;

      boolean result = true;
      result = result && (hasServerType() == other.hasServerType());
      if (hasServerType()) {
        result = result && (getServerType()
            == other.getServerType());
      }
      result = result && (hasGroupId() == other.hasGroupId());
      if (hasGroupId()) {
        result = result && (getGroupId()
            == other.getGroupId());
      }
      result = result && (hasSubId() == other.hasSubId());
      if (hasSubId()) {
        result = result && (getSubId()
            == other.getSubId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServerType()) {
        hash = (37 * hash) + SERVERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getServerType();
      }
      if (hasGroupId()) {
        hash = (37 * hash) + GROUPID_FIELD_NUMBER;
        hash = (53 * hash) + getGroupId();
      }
      if (hasSubId()) {
        hash = (37 * hash) + SUBID_FIELD_NUMBER;
        hash = (53 * hash) + getSubId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.server.register.ServerRegister.MSG_REQ_Server_Register prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.server.register.MSG_REQ_Server_Register}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.server.register.MSG_REQ_Server_Register)
        protocol.server.register.ServerRegister.MSG_REQ_Server_RegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_REQ_Server_Register_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_REQ_Server_Register_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.server.register.ServerRegister.MSG_REQ_Server_Register.class, protocol.server.register.ServerRegister.MSG_REQ_Server_Register.Builder.class);
      }

      // Construct using protocol.server.register.ServerRegister.MSG_REQ_Server_Register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        subId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_REQ_Server_Register_descriptor;
      }

      public protocol.server.register.ServerRegister.MSG_REQ_Server_Register getDefaultInstanceForType() {
        return protocol.server.register.ServerRegister.MSG_REQ_Server_Register.getDefaultInstance();
      }

      public protocol.server.register.ServerRegister.MSG_REQ_Server_Register build() {
        protocol.server.register.ServerRegister.MSG_REQ_Server_Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.server.register.ServerRegister.MSG_REQ_Server_Register buildPartial() {
        protocol.server.register.ServerRegister.MSG_REQ_Server_Register result = new protocol.server.register.ServerRegister.MSG_REQ_Server_Register(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverType_ = serverType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.groupId_ = groupId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.subId_ = subId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.server.register.ServerRegister.MSG_REQ_Server_Register) {
          return mergeFrom((protocol.server.register.ServerRegister.MSG_REQ_Server_Register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.server.register.ServerRegister.MSG_REQ_Server_Register other) {
        if (other == protocol.server.register.ServerRegister.MSG_REQ_Server_Register.getDefaultInstance()) return this;
        if (other.hasServerType()) {
          setServerType(other.getServerType());
        }
        if (other.hasGroupId()) {
          setGroupId(other.getGroupId());
        }
        if (other.hasSubId()) {
          setSubId(other.getSubId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.server.register.ServerRegister.MSG_REQ_Server_Register parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.server.register.ServerRegister.MSG_REQ_Server_Register) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverType_ ;
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public boolean hasServerType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public int getServerType() {
        return serverType_;
      }
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public Builder setServerType(int value) {
        bitField0_ |= 0x00000001;
        serverType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public Builder clearServerType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverType_ = 0;
        onChanged();
        return this;
      }

      private int groupId_ ;
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public Builder setGroupId(int value) {
        bitField0_ |= 0x00000002;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        groupId_ = 0;
        onChanged();
        return this;
      }

      private int subId_ ;
      /**
       * <code>optional int32 subId = 3;</code>
       */
      public boolean hasSubId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 subId = 3;</code>
       */
      public int getSubId() {
        return subId_;
      }
      /**
       * <code>optional int32 subId = 3;</code>
       */
      public Builder setSubId(int value) {
        bitField0_ |= 0x00000004;
        subId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 subId = 3;</code>
       */
      public Builder clearSubId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        subId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.server.register.MSG_REQ_Server_Register)
    }

    // @@protoc_insertion_point(class_scope:protocol.server.register.MSG_REQ_Server_Register)
    private static final protocol.server.register.ServerRegister.MSG_REQ_Server_Register DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.server.register.ServerRegister.MSG_REQ_Server_Register();
    }

    public static protocol.server.register.ServerRegister.MSG_REQ_Server_Register getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MSG_REQ_Server_Register>
        PARSER = new com.google.protobuf.AbstractParser<MSG_REQ_Server_Register>() {
      public MSG_REQ_Server_Register parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_REQ_Server_Register(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MSG_REQ_Server_Register> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MSG_REQ_Server_Register> getParserForType() {
      return PARSER;
    }

    public protocol.server.register.ServerRegister.MSG_REQ_Server_Register getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MSG_RES_Server_RegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.server.register.MSG_RES_Server_Register)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 serverType = 1;</code>
     */
    boolean hasServerType();
    /**
     * <code>required int32 serverType = 1;</code>
     */
    int getServerType();

    /**
     * <code>optional int32 groupId = 2;</code>
     */
    boolean hasGroupId();
    /**
     * <code>optional int32 groupId = 2;</code>
     */
    int getGroupId();

    /**
     * <code>optional int32 subId = 3;</code>
     */
    boolean hasSubId();
    /**
     * <code>optional int32 subId = 3;</code>
     */
    int getSubId();

    /**
     * <code>required uint32 result = 4;</code>
     */
    boolean hasResult();
    /**
     * <code>required uint32 result = 4;</code>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code protocol.server.register.MSG_RES_Server_Register}
   */
  public  static final class MSG_RES_Server_Register extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.server.register.MSG_RES_Server_Register)
      MSG_RES_Server_RegisterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MSG_RES_Server_Register.newBuilder() to construct.
    private MSG_RES_Server_Register(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MSG_RES_Server_Register() {
      serverType_ = 0;
      groupId_ = 0;
      subId_ = 0;
      result_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_RES_Server_Register(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              groupId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              subId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              result_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_RES_Server_Register_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_RES_Server_Register_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.server.register.ServerRegister.MSG_RES_Server_Register.class, protocol.server.register.ServerRegister.MSG_RES_Server_Register.Builder.class);
    }

    private int bitField0_;
    public static final int SERVERTYPE_FIELD_NUMBER = 1;
    private int serverType_;
    /**
     * <code>required int32 serverType = 1;</code>
     */
    public boolean hasServerType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 serverType = 1;</code>
     */
    public int getServerType() {
      return serverType_;
    }

    public static final int GROUPID_FIELD_NUMBER = 2;
    private int groupId_;
    /**
     * <code>optional int32 groupId = 2;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 groupId = 2;</code>
     */
    public int getGroupId() {
      return groupId_;
    }

    public static final int SUBID_FIELD_NUMBER = 3;
    private int subId_;
    /**
     * <code>optional int32 subId = 3;</code>
     */
    public boolean hasSubId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 subId = 3;</code>
     */
    public int getSubId() {
      return subId_;
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private int result_;
    /**
     * <code>required uint32 result = 4;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 result = 4;</code>
     */
    public int getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, groupId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, subId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, result_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, groupId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, subId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.server.register.ServerRegister.MSG_RES_Server_Register)) {
        return super.equals(obj);
      }
      protocol.server.register.ServerRegister.MSG_RES_Server_Register other = (protocol.server.register.ServerRegister.MSG_RES_Server_Register) obj;

      boolean result = true;
      result = result && (hasServerType() == other.hasServerType());
      if (hasServerType()) {
        result = result && (getServerType()
            == other.getServerType());
      }
      result = result && (hasGroupId() == other.hasGroupId());
      if (hasGroupId()) {
        result = result && (getGroupId()
            == other.getGroupId());
      }
      result = result && (hasSubId() == other.hasSubId());
      if (hasSubId()) {
        result = result && (getSubId()
            == other.getSubId());
      }
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && (getResult()
            == other.getResult());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServerType()) {
        hash = (37 * hash) + SERVERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getServerType();
      }
      if (hasGroupId()) {
        hash = (37 * hash) + GROUPID_FIELD_NUMBER;
        hash = (53 * hash) + getGroupId();
      }
      if (hasSubId()) {
        hash = (37 * hash) + SUBID_FIELD_NUMBER;
        hash = (53 * hash) + getSubId();
      }
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.server.register.ServerRegister.MSG_RES_Server_Register prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.server.register.MSG_RES_Server_Register}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.server.register.MSG_RES_Server_Register)
        protocol.server.register.ServerRegister.MSG_RES_Server_RegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_RES_Server_Register_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_RES_Server_Register_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.server.register.ServerRegister.MSG_RES_Server_Register.class, protocol.server.register.ServerRegister.MSG_RES_Server_Register.Builder.class);
      }

      // Construct using protocol.server.register.ServerRegister.MSG_RES_Server_Register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        subId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.server.register.ServerRegister.internal_static_protocol_server_register_MSG_RES_Server_Register_descriptor;
      }

      public protocol.server.register.ServerRegister.MSG_RES_Server_Register getDefaultInstanceForType() {
        return protocol.server.register.ServerRegister.MSG_RES_Server_Register.getDefaultInstance();
      }

      public protocol.server.register.ServerRegister.MSG_RES_Server_Register build() {
        protocol.server.register.ServerRegister.MSG_RES_Server_Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.server.register.ServerRegister.MSG_RES_Server_Register buildPartial() {
        protocol.server.register.ServerRegister.MSG_RES_Server_Register result = new protocol.server.register.ServerRegister.MSG_RES_Server_Register(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverType_ = serverType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.groupId_ = groupId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.subId_ = subId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.server.register.ServerRegister.MSG_RES_Server_Register) {
          return mergeFrom((protocol.server.register.ServerRegister.MSG_RES_Server_Register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.server.register.ServerRegister.MSG_RES_Server_Register other) {
        if (other == protocol.server.register.ServerRegister.MSG_RES_Server_Register.getDefaultInstance()) return this;
        if (other.hasServerType()) {
          setServerType(other.getServerType());
        }
        if (other.hasGroupId()) {
          setGroupId(other.getGroupId());
        }
        if (other.hasSubId()) {
          setSubId(other.getSubId());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerType()) {
          return false;
        }
        if (!hasResult()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.server.register.ServerRegister.MSG_RES_Server_Register parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.server.register.ServerRegister.MSG_RES_Server_Register) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverType_ ;
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public boolean hasServerType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public int getServerType() {
        return serverType_;
      }
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public Builder setServerType(int value) {
        bitField0_ |= 0x00000001;
        serverType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public Builder clearServerType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverType_ = 0;
        onChanged();
        return this;
      }

      private int groupId_ ;
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public Builder setGroupId(int value) {
        bitField0_ |= 0x00000002;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        groupId_ = 0;
        onChanged();
        return this;
      }

      private int subId_ ;
      /**
       * <code>optional int32 subId = 3;</code>
       */
      public boolean hasSubId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 subId = 3;</code>
       */
      public int getSubId() {
        return subId_;
      }
      /**
       * <code>optional int32 subId = 3;</code>
       */
      public Builder setSubId(int value) {
        bitField0_ |= 0x00000004;
        subId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 subId = 3;</code>
       */
      public Builder clearSubId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        subId_ = 0;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>required uint32 result = 4;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 result = 4;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required uint32 result = 4;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000008;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 result = 4;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000008);
        result_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.server.register.MSG_RES_Server_Register)
    }

    // @@protoc_insertion_point(class_scope:protocol.server.register.MSG_RES_Server_Register)
    private static final protocol.server.register.ServerRegister.MSG_RES_Server_Register DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.server.register.ServerRegister.MSG_RES_Server_Register();
    }

    public static protocol.server.register.ServerRegister.MSG_RES_Server_Register getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MSG_RES_Server_Register>
        PARSER = new com.google.protobuf.AbstractParser<MSG_RES_Server_Register>() {
      public MSG_RES_Server_Register parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_RES_Server_Register(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MSG_RES_Server_Register> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MSG_RES_Server_Register> getParserForType() {
      return PARSER;
    }

    public protocol.server.register.ServerRegister.MSG_RES_Server_Register getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConnectInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.server.register.ConnectInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 port = 1;</code>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 1;</code>
     */
    int getPort();

    /**
     * <code>required string ip = 2;</code>
     */
    boolean hasIp();
    /**
     * <code>required string ip = 2;</code>
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();
  }
  /**
   * Protobuf type {@code protocol.server.register.ConnectInfo}
   */
  public  static final class ConnectInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.server.register.ConnectInfo)
      ConnectInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConnectInfo.newBuilder() to construct.
    private ConnectInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectInfo() {
      port_ = 0;
      ip_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConnectInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              port_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ip_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.server.register.ServerRegister.internal_static_protocol_server_register_ConnectInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.server.register.ServerRegister.internal_static_protocol_server_register_ConnectInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.server.register.ServerRegister.ConnectInfo.class, protocol.server.register.ServerRegister.ConnectInfo.Builder.class);
    }

    private int bitField0_;
    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    /**
     * <code>required int32 port = 1;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 port = 1;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object ip_;
    /**
     * <code>required string ip = 2;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ip = 2;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.server.register.ServerRegister.ConnectInfo)) {
        return super.equals(obj);
      }
      protocol.server.register.ServerRegister.ConnectInfo other = (protocol.server.register.ServerRegister.ConnectInfo) obj;

      boolean result = true;
      result = result && (hasPort() == other.hasPort());
      if (hasPort()) {
        result = result && (getPort()
            == other.getPort());
      }
      result = result && (hasIp() == other.hasIp());
      if (hasIp()) {
        result = result && getIp()
            .equals(other.getIp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.register.ServerRegister.ConnectInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.server.register.ServerRegister.ConnectInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.server.register.ConnectInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.server.register.ConnectInfo)
        protocol.server.register.ServerRegister.ConnectInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.server.register.ServerRegister.internal_static_protocol_server_register_ConnectInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.server.register.ServerRegister.internal_static_protocol_server_register_ConnectInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.server.register.ServerRegister.ConnectInfo.class, protocol.server.register.ServerRegister.ConnectInfo.Builder.class);
      }

      // Construct using protocol.server.register.ServerRegister.ConnectInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.server.register.ServerRegister.internal_static_protocol_server_register_ConnectInfo_descriptor;
      }

      public protocol.server.register.ServerRegister.ConnectInfo getDefaultInstanceForType() {
        return protocol.server.register.ServerRegister.ConnectInfo.getDefaultInstance();
      }

      public protocol.server.register.ServerRegister.ConnectInfo build() {
        protocol.server.register.ServerRegister.ConnectInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.server.register.ServerRegister.ConnectInfo buildPartial() {
        protocol.server.register.ServerRegister.ConnectInfo result = new protocol.server.register.ServerRegister.ConnectInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip_ = ip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.server.register.ServerRegister.ConnectInfo) {
          return mergeFrom((protocol.server.register.ServerRegister.ConnectInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.server.register.ServerRegister.ConnectInfo other) {
        if (other == protocol.server.register.ServerRegister.ConnectInfo.getDefaultInstance()) return this;
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000002;
          ip_ = other.ip_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPort()) {
          return false;
        }
        if (!hasIp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.server.register.ServerRegister.ConnectInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.server.register.ServerRegister.ConnectInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int port_ ;
      /**
       * <code>required int32 port = 1;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000001;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 2;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.server.register.ConnectInfo)
    }

    // @@protoc_insertion_point(class_scope:protocol.server.register.ConnectInfo)
    private static final protocol.server.register.ServerRegister.ConnectInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.server.register.ServerRegister.ConnectInfo();
    }

    public static protocol.server.register.ServerRegister.ConnectInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ConnectInfo>
        PARSER = new com.google.protobuf.AbstractParser<ConnectInfo>() {
      public ConnectInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConnectInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConnectInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectInfo> getParserForType() {
      return PARSER;
    }

    public protocol.server.register.ServerRegister.ConnectInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_server_register_MSG_REQ_Server_Register_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_server_register_MSG_REQ_Server_Register_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_server_register_MSG_RES_Server_Register_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_server_register_MSG_RES_Server_Register_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_server_register_ConnectInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_server_register_ConnectInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ServerRegister.proto\022\030protocol.server." +
      "register\"M\n\027MSG_REQ_Server_Register\022\022\n\ns" +
      "erverType\030\001 \002(\005\022\017\n\007groupId\030\002 \001(\005\022\r\n\005subI" +
      "d\030\003 \001(\005\"]\n\027MSG_RES_Server_Register\022\022\n\nse" +
      "rverType\030\001 \002(\005\022\017\n\007groupId\030\002 \001(\005\022\r\n\005subId" +
      "\030\003 \001(\005\022\016\n\006result\030\004 \002(\r\"\'\n\013ConnectInfo\022\014\n" +
      "\004port\030\001 \002(\005\022\n\n\002ip\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_server_register_MSG_REQ_Server_Register_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_server_register_MSG_REQ_Server_Register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_server_register_MSG_REQ_Server_Register_descriptor,
        new java.lang.String[] { "ServerType", "GroupId", "SubId", });
    internal_static_protocol_server_register_MSG_RES_Server_Register_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_server_register_MSG_RES_Server_Register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_server_register_MSG_RES_Server_Register_descriptor,
        new java.lang.String[] { "ServerType", "GroupId", "SubId", "Result", });
    internal_static_protocol_server_register_ConnectInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_server_register_ConnectInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_server_register_ConnectInfo_descriptor,
        new java.lang.String[] { "Port", "Ip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
