 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
namespace Protocol.Client.Gate
{
     public class IdGen
     {
          public static void GenerateId()
          {
               Protocol.MsgIdId<C2GTest1>.Value= 0x1200001;
               Protocol.MsgIdId<C2GTest2>.Value= 0x1200002;
               Protocol.MsgIdId<C2GTest3>.Value= 0x1200003;
          }
     }
}
