// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2C.proto

package protocol.server.client;

public final class S2C {
  private S2C() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CSLoginInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.server.client.CSLoginInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string UserName = 1;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string UserName = 1;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string UserName = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>required string Password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string Password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string Password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code protocol.server.client.CSLoginInfo}
   */
  public  static final class CSLoginInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.server.client.CSLoginInfo)
      CSLoginInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSLoginInfo.newBuilder() to construct.
    private CSLoginInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSLoginInfo() {
      userName_ = "";
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSLoginInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.server.client.S2C.CSLoginInfo.class, protocol.server.client.S2C.CSLoginInfo.Builder.class);
    }

    private int bitField0_;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object userName_;
    /**
     * <code>required string UserName = 1;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string UserName = 1;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string UserName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>required string Password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string Password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.server.client.S2C.CSLoginInfo)) {
        return super.equals(obj);
      }
      protocol.server.client.S2C.CSLoginInfo other = (protocol.server.client.S2C.CSLoginInfo) obj;

      boolean result = true;
      result = result && (hasUserName() == other.hasUserName());
      if (hasUserName()) {
        result = result && getUserName()
            .equals(other.getUserName());
      }
      result = result && (hasPassword() == other.hasPassword());
      if (hasPassword()) {
        result = result && getPassword()
            .equals(other.getPassword());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserName()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
      }
      if (hasPassword()) {
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.server.client.S2C.CSLoginInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.client.S2C.CSLoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.server.client.S2C.CSLoginInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.server.client.CSLoginInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.server.client.CSLoginInfo)
        protocol.server.client.S2C.CSLoginInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.server.client.S2C.CSLoginInfo.class, protocol.server.client.S2C.CSLoginInfo.Builder.class);
      }

      // Construct using protocol.server.client.S2C.CSLoginInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginInfo_descriptor;
      }

      public protocol.server.client.S2C.CSLoginInfo getDefaultInstanceForType() {
        return protocol.server.client.S2C.CSLoginInfo.getDefaultInstance();
      }

      public protocol.server.client.S2C.CSLoginInfo build() {
        protocol.server.client.S2C.CSLoginInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.server.client.S2C.CSLoginInfo buildPartial() {
        protocol.server.client.S2C.CSLoginInfo result = new protocol.server.client.S2C.CSLoginInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.server.client.S2C.CSLoginInfo) {
          return mergeFrom((protocol.server.client.S2C.CSLoginInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.server.client.S2C.CSLoginInfo other) {
        if (other == protocol.server.client.S2C.CSLoginInfo.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          bitField0_ |= 0x00000001;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserName()) {
          return false;
        }
        if (!hasPassword()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.server.client.S2C.CSLoginInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.server.client.S2C.CSLoginInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userName_ = "";
      /**
       * <code>required string UserName = 1;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string UserName = 1;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string UserName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string UserName = 1;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string UserName = 1;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string UserName = 1;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string Password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.server.client.CSLoginInfo)
    }

    // @@protoc_insertion_point(class_scope:protocol.server.client.CSLoginInfo)
    private static final protocol.server.client.S2C.CSLoginInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.server.client.S2C.CSLoginInfo();
    }

    public static protocol.server.client.S2C.CSLoginInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CSLoginInfo>
        PARSER = new com.google.protobuf.AbstractParser<CSLoginInfo>() {
      public CSLoginInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSLoginInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSLoginInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSLoginInfo> getParserForType() {
      return PARSER;
    }

    public protocol.server.client.S2C.CSLoginInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CSLoginReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.server.client.CSLoginReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
     */
    boolean hasLoginInfo();
    /**
     * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
     */
    protocol.server.client.S2C.CSLoginInfo getLoginInfo();
    /**
     * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
     */
    protocol.server.client.S2C.CSLoginInfoOrBuilder getLoginInfoOrBuilder();

    /**
     * <code>required string teststring2 = 2;</code>
     */
    boolean hasTeststring2();
    /**
     * <code>required string teststring2 = 2;</code>
     */
    java.lang.String getTeststring2();
    /**
     * <code>required string teststring2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getTeststring2Bytes();
  }
  /**
   * Protobuf type {@code protocol.server.client.CSLoginReq}
   */
  public  static final class CSLoginReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.server.client.CSLoginReq)
      CSLoginReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSLoginReq.newBuilder() to construct.
    private CSLoginReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSLoginReq() {
      teststring2_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSLoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol.server.client.S2C.CSLoginInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = loginInfo_.toBuilder();
              }
              loginInfo_ = input.readMessage(protocol.server.client.S2C.CSLoginInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loginInfo_);
                loginInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              teststring2_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.server.client.S2C.CSLoginReq.class, protocol.server.client.S2C.CSLoginReq.Builder.class);
    }

    private int bitField0_;
    public static final int LOGININFO_FIELD_NUMBER = 1;
    private protocol.server.client.S2C.CSLoginInfo loginInfo_;
    /**
     * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
     */
    public boolean hasLoginInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
     */
    public protocol.server.client.S2C.CSLoginInfo getLoginInfo() {
      return loginInfo_ == null ? protocol.server.client.S2C.CSLoginInfo.getDefaultInstance() : loginInfo_;
    }
    /**
     * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
     */
    public protocol.server.client.S2C.CSLoginInfoOrBuilder getLoginInfoOrBuilder() {
      return loginInfo_ == null ? protocol.server.client.S2C.CSLoginInfo.getDefaultInstance() : loginInfo_;
    }

    public static final int TESTSTRING2_FIELD_NUMBER = 2;
    private volatile java.lang.Object teststring2_;
    /**
     * <code>required string teststring2 = 2;</code>
     */
    public boolean hasTeststring2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string teststring2 = 2;</code>
     */
    public java.lang.String getTeststring2() {
      java.lang.Object ref = teststring2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teststring2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string teststring2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTeststring2Bytes() {
      java.lang.Object ref = teststring2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teststring2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLoginInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeststring2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getLoginInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getLoginInfo());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, teststring2_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginInfo());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, teststring2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.server.client.S2C.CSLoginReq)) {
        return super.equals(obj);
      }
      protocol.server.client.S2C.CSLoginReq other = (protocol.server.client.S2C.CSLoginReq) obj;

      boolean result = true;
      result = result && (hasLoginInfo() == other.hasLoginInfo());
      if (hasLoginInfo()) {
        result = result && getLoginInfo()
            .equals(other.getLoginInfo());
      }
      result = result && (hasTeststring2() == other.hasTeststring2());
      if (hasTeststring2()) {
        result = result && getTeststring2()
            .equals(other.getTeststring2());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLoginInfo()) {
        hash = (37 * hash) + LOGININFO_FIELD_NUMBER;
        hash = (53 * hash) + getLoginInfo().hashCode();
      }
      if (hasTeststring2()) {
        hash = (37 * hash) + TESTSTRING2_FIELD_NUMBER;
        hash = (53 * hash) + getTeststring2().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.server.client.S2C.CSLoginReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.client.S2C.CSLoginReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.client.S2C.CSLoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.client.S2C.CSLoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.client.S2C.CSLoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.server.client.S2C.CSLoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.client.S2C.CSLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.server.client.S2C.CSLoginReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.server.client.CSLoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.server.client.CSLoginReq)
        protocol.server.client.S2C.CSLoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.server.client.S2C.CSLoginReq.class, protocol.server.client.S2C.CSLoginReq.Builder.class);
      }

      // Construct using protocol.server.client.S2C.CSLoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLoginInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (loginInfoBuilder_ == null) {
          loginInfo_ = null;
        } else {
          loginInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        teststring2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginReq_descriptor;
      }

      public protocol.server.client.S2C.CSLoginReq getDefaultInstanceForType() {
        return protocol.server.client.S2C.CSLoginReq.getDefaultInstance();
      }

      public protocol.server.client.S2C.CSLoginReq build() {
        protocol.server.client.S2C.CSLoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.server.client.S2C.CSLoginReq buildPartial() {
        protocol.server.client.S2C.CSLoginReq result = new protocol.server.client.S2C.CSLoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (loginInfoBuilder_ == null) {
          result.loginInfo_ = loginInfo_;
        } else {
          result.loginInfo_ = loginInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teststring2_ = teststring2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.server.client.S2C.CSLoginReq) {
          return mergeFrom((protocol.server.client.S2C.CSLoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.server.client.S2C.CSLoginReq other) {
        if (other == protocol.server.client.S2C.CSLoginReq.getDefaultInstance()) return this;
        if (other.hasLoginInfo()) {
          mergeLoginInfo(other.getLoginInfo());
        }
        if (other.hasTeststring2()) {
          bitField0_ |= 0x00000002;
          teststring2_ = other.teststring2_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLoginInfo()) {
          return false;
        }
        if (!hasTeststring2()) {
          return false;
        }
        if (!getLoginInfo().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.server.client.S2C.CSLoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.server.client.S2C.CSLoginReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol.server.client.S2C.CSLoginInfo loginInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.server.client.S2C.CSLoginInfo, protocol.server.client.S2C.CSLoginInfo.Builder, protocol.server.client.S2C.CSLoginInfoOrBuilder> loginInfoBuilder_;
      /**
       * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
       */
      public boolean hasLoginInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
       */
      public protocol.server.client.S2C.CSLoginInfo getLoginInfo() {
        if (loginInfoBuilder_ == null) {
          return loginInfo_ == null ? protocol.server.client.S2C.CSLoginInfo.getDefaultInstance() : loginInfo_;
        } else {
          return loginInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
       */
      public Builder setLoginInfo(protocol.server.client.S2C.CSLoginInfo value) {
        if (loginInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginInfo_ = value;
          onChanged();
        } else {
          loginInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
       */
      public Builder setLoginInfo(
          protocol.server.client.S2C.CSLoginInfo.Builder builderForValue) {
        if (loginInfoBuilder_ == null) {
          loginInfo_ = builderForValue.build();
          onChanged();
        } else {
          loginInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
       */
      public Builder mergeLoginInfo(protocol.server.client.S2C.CSLoginInfo value) {
        if (loginInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              loginInfo_ != null &&
              loginInfo_ != protocol.server.client.S2C.CSLoginInfo.getDefaultInstance()) {
            loginInfo_ =
              protocol.server.client.S2C.CSLoginInfo.newBuilder(loginInfo_).mergeFrom(value).buildPartial();
          } else {
            loginInfo_ = value;
          }
          onChanged();
        } else {
          loginInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
       */
      public Builder clearLoginInfo() {
        if (loginInfoBuilder_ == null) {
          loginInfo_ = null;
          onChanged();
        } else {
          loginInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
       */
      public protocol.server.client.S2C.CSLoginInfo.Builder getLoginInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getLoginInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
       */
      public protocol.server.client.S2C.CSLoginInfoOrBuilder getLoginInfoOrBuilder() {
        if (loginInfoBuilder_ != null) {
          return loginInfoBuilder_.getMessageOrBuilder();
        } else {
          return loginInfo_ == null ?
              protocol.server.client.S2C.CSLoginInfo.getDefaultInstance() : loginInfo_;
        }
      }
      /**
       * <code>required .protocol.server.client.CSLoginInfo LoginInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.server.client.S2C.CSLoginInfo, protocol.server.client.S2C.CSLoginInfo.Builder, protocol.server.client.S2C.CSLoginInfoOrBuilder> 
          getLoginInfoFieldBuilder() {
        if (loginInfoBuilder_ == null) {
          loginInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.server.client.S2C.CSLoginInfo, protocol.server.client.S2C.CSLoginInfo.Builder, protocol.server.client.S2C.CSLoginInfoOrBuilder>(
                  getLoginInfo(),
                  getParentForChildren(),
                  isClean());
          loginInfo_ = null;
        }
        return loginInfoBuilder_;
      }

      private java.lang.Object teststring2_ = "";
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public boolean hasTeststring2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public java.lang.String getTeststring2() {
        java.lang.Object ref = teststring2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            teststring2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTeststring2Bytes() {
        java.lang.Object ref = teststring2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teststring2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public Builder setTeststring2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public Builder clearTeststring2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teststring2_ = getDefaultInstance().getTeststring2();
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public Builder setTeststring2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring2_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.server.client.CSLoginReq)
    }

    // @@protoc_insertion_point(class_scope:protocol.server.client.CSLoginReq)
    private static final protocol.server.client.S2C.CSLoginReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.server.client.S2C.CSLoginReq();
    }

    public static protocol.server.client.S2C.CSLoginReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CSLoginReq>
        PARSER = new com.google.protobuf.AbstractParser<CSLoginReq>() {
      public CSLoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSLoginReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSLoginReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSLoginReq> getParserForType() {
      return PARSER;
    }

    public protocol.server.client.S2C.CSLoginReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CSLoginResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.server.client.CSLoginRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 result_code = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required uint32 result_code = 1;</code>
     */
    int getResultCode();
  }
  /**
   * Protobuf type {@code protocol.server.client.CSLoginRes}
   */
  public  static final class CSLoginRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.server.client.CSLoginRes)
      CSLoginResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSLoginRes.newBuilder() to construct.
    private CSLoginRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSLoginRes() {
      resultCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSLoginRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultCode_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.server.client.S2C.CSLoginRes.class, protocol.server.client.S2C.CSLoginRes.Builder.class);
    }

    private int bitField0_;
    public static final int RESULT_CODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <code>required uint32 result_code = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 result_code = 1;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, resultCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, resultCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.server.client.S2C.CSLoginRes)) {
        return super.equals(obj);
      }
      protocol.server.client.S2C.CSLoginRes other = (protocol.server.client.S2C.CSLoginRes) obj;

      boolean result = true;
      result = result && (hasResultCode() == other.hasResultCode());
      if (hasResultCode()) {
        result = result && (getResultCode()
            == other.getResultCode());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResultCode()) {
        hash = (37 * hash) + RESULT_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getResultCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.server.client.S2C.CSLoginRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.client.S2C.CSLoginRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.client.S2C.CSLoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.server.client.S2C.CSLoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.client.S2C.CSLoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.server.client.S2C.CSLoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.server.client.S2C.CSLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.server.client.S2C.CSLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.server.client.S2C.CSLoginRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.server.client.CSLoginRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.server.client.CSLoginRes)
        protocol.server.client.S2C.CSLoginResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.server.client.S2C.CSLoginRes.class, protocol.server.client.S2C.CSLoginRes.Builder.class);
      }

      // Construct using protocol.server.client.S2C.CSLoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.server.client.S2C.internal_static_protocol_server_client_CSLoginRes_descriptor;
      }

      public protocol.server.client.S2C.CSLoginRes getDefaultInstanceForType() {
        return protocol.server.client.S2C.CSLoginRes.getDefaultInstance();
      }

      public protocol.server.client.S2C.CSLoginRes build() {
        protocol.server.client.S2C.CSLoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.server.client.S2C.CSLoginRes buildPartial() {
        protocol.server.client.S2C.CSLoginRes result = new protocol.server.client.S2C.CSLoginRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.server.client.S2C.CSLoginRes) {
          return mergeFrom((protocol.server.client.S2C.CSLoginRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.server.client.S2C.CSLoginRes other) {
        if (other == protocol.server.client.S2C.CSLoginRes.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.server.client.S2C.CSLoginRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.server.client.S2C.CSLoginRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int resultCode_ ;
      /**
       * <code>required uint32 result_code = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 result_code = 1;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required uint32 result_code = 1;</code>
       */
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 result_code = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.server.client.CSLoginRes)
    }

    // @@protoc_insertion_point(class_scope:protocol.server.client.CSLoginRes)
    private static final protocol.server.client.S2C.CSLoginRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.server.client.S2C.CSLoginRes();
    }

    public static protocol.server.client.S2C.CSLoginRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CSLoginRes>
        PARSER = new com.google.protobuf.AbstractParser<CSLoginRes>() {
      public CSLoginRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSLoginRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSLoginRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSLoginRes> getParserForType() {
      return PARSER;
    }

    public protocol.server.client.S2C.CSLoginRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_server_client_CSLoginInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_server_client_CSLoginInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_server_client_CSLoginReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_server_client_CSLoginReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_server_client_CSLoginRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_server_client_CSLoginRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tS2C.proto\022\026protocol.server.client\"1\n\013C" +
      "SLoginInfo\022\020\n\010UserName\030\001 \002(\t\022\020\n\010Password" +
      "\030\002 \002(\t\"Y\n\nCSLoginReq\0226\n\tLoginInfo\030\001 \002(\0132" +
      "#.protocol.server.client.CSLoginInfo\022\023\n\013" +
      "teststring2\030\002 \002(\t\"!\n\nCSLoginRes\022\023\n\013resul" +
      "t_code\030\001 \002(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_server_client_CSLoginInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_server_client_CSLoginInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_server_client_CSLoginInfo_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_protocol_server_client_CSLoginReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_server_client_CSLoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_server_client_CSLoginReq_descriptor,
        new java.lang.String[] { "LoginInfo", "Teststring2", });
    internal_static_protocol_server_client_CSLoginRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_server_client_CSLoginRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_server_client_CSLoginRes_descriptor,
        new java.lang.String[] { "ResultCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
