 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
namespace protocol.server.client
{
     public class IdGenerater
     {
          public static void GenerateId()
          {
               Protocol.MsgId.Id<CSLoginInfo>.Value= 0x2100001;
               Protocol.MsgId.Id<CSLoginReq>.Value= 0x2100002;
               Protocol.MsgId.Id<CSLoginRes>.Value= 0x2100003;
          }
     }
}
