//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Protocol/Client/Enum.proto
namespace protocol.client.server
{
    [global::ProtoBuf.ProtoContract(Name=@"EnmCmdID")]
    public enum EnmCmdID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGIN_REQ", Value=10001)]
      CS_LOGIN_REQ = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGIN_RES", Value=10002)]
      CS_LOGIN_RES = 10002
    }
  
}