// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2G.proto

package protocol.client.gate;

public final class C2G {
  private C2G() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2GTest1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.client.gate.C2GTest1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 testint1 = 1;</code>
     */
    boolean hasTestint1();
    /**
     * <code>required int32 testint1 = 1;</code>
     */
    int getTestint1();

    /**
     * <code>required string teststring1 = 2;</code>
     */
    boolean hasTeststring1();
    /**
     * <code>required string teststring1 = 2;</code>
     */
    java.lang.String getTeststring1();
    /**
     * <code>required string teststring1 = 2;</code>
     */
    com.google.protobuf.ByteString
        getTeststring1Bytes();

    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    java.util.List<protocol.client.gate.C2G.C2GTest2> 
        getC2GTest2ListList();
    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    protocol.client.gate.C2G.C2GTest2 getC2GTest2List(int index);
    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    int getC2GTest2ListCount();
    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    java.util.List<? extends protocol.client.gate.C2G.C2GTest2OrBuilder> 
        getC2GTest2ListOrBuilderList();
    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    protocol.client.gate.C2G.C2GTest2OrBuilder getC2GTest2ListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocol.client.gate.C2GTest1}
   */
  public  static final class C2GTest1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.client.gate.C2GTest1)
      C2GTest1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2GTest1.newBuilder() to construct.
    private C2GTest1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2GTest1() {
      testint1_ = 0;
      teststring1_ = "";
      c2GTest2List_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2GTest1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              testint1_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              teststring1_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                c2GTest2List_ = new java.util.ArrayList<protocol.client.gate.C2G.C2GTest2>();
                mutable_bitField0_ |= 0x00000004;
              }
              c2GTest2List_.add(
                  input.readMessage(protocol.client.gate.C2G.C2GTest2.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          c2GTest2List_ = java.util.Collections.unmodifiableList(c2GTest2List_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.client.gate.C2G.C2GTest1.class, protocol.client.gate.C2G.C2GTest1.Builder.class);
    }

    private int bitField0_;
    public static final int TESTINT1_FIELD_NUMBER = 1;
    private int testint1_;
    /**
     * <code>required int32 testint1 = 1;</code>
     */
    public boolean hasTestint1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 testint1 = 1;</code>
     */
    public int getTestint1() {
      return testint1_;
    }

    public static final int TESTSTRING1_FIELD_NUMBER = 2;
    private volatile java.lang.Object teststring1_;
    /**
     * <code>required string teststring1 = 2;</code>
     */
    public boolean hasTeststring1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string teststring1 = 2;</code>
     */
    public java.lang.String getTeststring1() {
      java.lang.Object ref = teststring1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teststring1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string teststring1 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTeststring1Bytes() {
      java.lang.Object ref = teststring1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teststring1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C2GTEST2LIST_FIELD_NUMBER = 3;
    private java.util.List<protocol.client.gate.C2G.C2GTest2> c2GTest2List_;
    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    public java.util.List<protocol.client.gate.C2G.C2GTest2> getC2GTest2ListList() {
      return c2GTest2List_;
    }
    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    public java.util.List<? extends protocol.client.gate.C2G.C2GTest2OrBuilder> 
        getC2GTest2ListOrBuilderList() {
      return c2GTest2List_;
    }
    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    public int getC2GTest2ListCount() {
      return c2GTest2List_.size();
    }
    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    public protocol.client.gate.C2G.C2GTest2 getC2GTest2List(int index) {
      return c2GTest2List_.get(index);
    }
    /**
     * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
     */
    public protocol.client.gate.C2G.C2GTest2OrBuilder getC2GTest2ListOrBuilder(
        int index) {
      return c2GTest2List_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTestint1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeststring1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getC2GTest2ListCount(); i++) {
        if (!getC2GTest2List(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, testint1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, teststring1_);
      }
      for (int i = 0; i < c2GTest2List_.size(); i++) {
        output.writeMessage(3, c2GTest2List_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, testint1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, teststring1_);
      }
      for (int i = 0; i < c2GTest2List_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, c2GTest2List_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.client.gate.C2G.C2GTest1)) {
        return super.equals(obj);
      }
      protocol.client.gate.C2G.C2GTest1 other = (protocol.client.gate.C2G.C2GTest1) obj;

      boolean result = true;
      result = result && (hasTestint1() == other.hasTestint1());
      if (hasTestint1()) {
        result = result && (getTestint1()
            == other.getTestint1());
      }
      result = result && (hasTeststring1() == other.hasTeststring1());
      if (hasTeststring1()) {
        result = result && getTeststring1()
            .equals(other.getTeststring1());
      }
      result = result && getC2GTest2ListList()
          .equals(other.getC2GTest2ListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestint1()) {
        hash = (37 * hash) + TESTINT1_FIELD_NUMBER;
        hash = (53 * hash) + getTestint1();
      }
      if (hasTeststring1()) {
        hash = (37 * hash) + TESTSTRING1_FIELD_NUMBER;
        hash = (53 * hash) + getTeststring1().hashCode();
      }
      if (getC2GTest2ListCount() > 0) {
        hash = (37 * hash) + C2GTEST2LIST_FIELD_NUMBER;
        hash = (53 * hash) + getC2GTest2ListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.client.gate.C2G.C2GTest1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.client.gate.C2G.C2GTest1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.client.gate.C2G.C2GTest1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.client.gate.C2GTest1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.client.gate.C2GTest1)
        protocol.client.gate.C2G.C2GTest1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.client.gate.C2G.C2GTest1.class, protocol.client.gate.C2G.C2GTest1.Builder.class);
      }

      // Construct using protocol.client.gate.C2G.C2GTest1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getC2GTest2ListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        testint1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        teststring1_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (c2GTest2ListBuilder_ == null) {
          c2GTest2List_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          c2GTest2ListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest1_descriptor;
      }

      public protocol.client.gate.C2G.C2GTest1 getDefaultInstanceForType() {
        return protocol.client.gate.C2G.C2GTest1.getDefaultInstance();
      }

      public protocol.client.gate.C2G.C2GTest1 build() {
        protocol.client.gate.C2G.C2GTest1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.client.gate.C2G.C2GTest1 buildPartial() {
        protocol.client.gate.C2G.C2GTest1 result = new protocol.client.gate.C2G.C2GTest1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testint1_ = testint1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teststring1_ = teststring1_;
        if (c2GTest2ListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            c2GTest2List_ = java.util.Collections.unmodifiableList(c2GTest2List_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.c2GTest2List_ = c2GTest2List_;
        } else {
          result.c2GTest2List_ = c2GTest2ListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.client.gate.C2G.C2GTest1) {
          return mergeFrom((protocol.client.gate.C2G.C2GTest1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.client.gate.C2G.C2GTest1 other) {
        if (other == protocol.client.gate.C2G.C2GTest1.getDefaultInstance()) return this;
        if (other.hasTestint1()) {
          setTestint1(other.getTestint1());
        }
        if (other.hasTeststring1()) {
          bitField0_ |= 0x00000002;
          teststring1_ = other.teststring1_;
          onChanged();
        }
        if (c2GTest2ListBuilder_ == null) {
          if (!other.c2GTest2List_.isEmpty()) {
            if (c2GTest2List_.isEmpty()) {
              c2GTest2List_ = other.c2GTest2List_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureC2GTest2ListIsMutable();
              c2GTest2List_.addAll(other.c2GTest2List_);
            }
            onChanged();
          }
        } else {
          if (!other.c2GTest2List_.isEmpty()) {
            if (c2GTest2ListBuilder_.isEmpty()) {
              c2GTest2ListBuilder_.dispose();
              c2GTest2ListBuilder_ = null;
              c2GTest2List_ = other.c2GTest2List_;
              bitField0_ = (bitField0_ & ~0x00000004);
              c2GTest2ListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getC2GTest2ListFieldBuilder() : null;
            } else {
              c2GTest2ListBuilder_.addAllMessages(other.c2GTest2List_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestint1()) {
          return false;
        }
        if (!hasTeststring1()) {
          return false;
        }
        for (int i = 0; i < getC2GTest2ListCount(); i++) {
          if (!getC2GTest2List(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.client.gate.C2G.C2GTest1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.client.gate.C2G.C2GTest1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int testint1_ ;
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public boolean hasTestint1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public int getTestint1() {
        return testint1_;
      }
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public Builder setTestint1(int value) {
        bitField0_ |= 0x00000001;
        testint1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public Builder clearTestint1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testint1_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object teststring1_ = "";
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public boolean hasTeststring1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public java.lang.String getTeststring1() {
        java.lang.Object ref = teststring1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            teststring1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTeststring1Bytes() {
        java.lang.Object ref = teststring1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teststring1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public Builder setTeststring1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public Builder clearTeststring1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teststring1_ = getDefaultInstance().getTeststring1();
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public Builder setTeststring1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring1_ = value;
        onChanged();
        return this;
      }

      private java.util.List<protocol.client.gate.C2G.C2GTest2> c2GTest2List_ =
        java.util.Collections.emptyList();
      private void ensureC2GTest2ListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          c2GTest2List_ = new java.util.ArrayList<protocol.client.gate.C2G.C2GTest2>(c2GTest2List_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.client.gate.C2G.C2GTest2, protocol.client.gate.C2G.C2GTest2.Builder, protocol.client.gate.C2G.C2GTest2OrBuilder> c2GTest2ListBuilder_;

      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public java.util.List<protocol.client.gate.C2G.C2GTest2> getC2GTest2ListList() {
        if (c2GTest2ListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(c2GTest2List_);
        } else {
          return c2GTest2ListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public int getC2GTest2ListCount() {
        if (c2GTest2ListBuilder_ == null) {
          return c2GTest2List_.size();
        } else {
          return c2GTest2ListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public protocol.client.gate.C2G.C2GTest2 getC2GTest2List(int index) {
        if (c2GTest2ListBuilder_ == null) {
          return c2GTest2List_.get(index);
        } else {
          return c2GTest2ListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public Builder setC2GTest2List(
          int index, protocol.client.gate.C2G.C2GTest2 value) {
        if (c2GTest2ListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureC2GTest2ListIsMutable();
          c2GTest2List_.set(index, value);
          onChanged();
        } else {
          c2GTest2ListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public Builder setC2GTest2List(
          int index, protocol.client.gate.C2G.C2GTest2.Builder builderForValue) {
        if (c2GTest2ListBuilder_ == null) {
          ensureC2GTest2ListIsMutable();
          c2GTest2List_.set(index, builderForValue.build());
          onChanged();
        } else {
          c2GTest2ListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public Builder addC2GTest2List(protocol.client.gate.C2G.C2GTest2 value) {
        if (c2GTest2ListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureC2GTest2ListIsMutable();
          c2GTest2List_.add(value);
          onChanged();
        } else {
          c2GTest2ListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public Builder addC2GTest2List(
          int index, protocol.client.gate.C2G.C2GTest2 value) {
        if (c2GTest2ListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureC2GTest2ListIsMutable();
          c2GTest2List_.add(index, value);
          onChanged();
        } else {
          c2GTest2ListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public Builder addC2GTest2List(
          protocol.client.gate.C2G.C2GTest2.Builder builderForValue) {
        if (c2GTest2ListBuilder_ == null) {
          ensureC2GTest2ListIsMutable();
          c2GTest2List_.add(builderForValue.build());
          onChanged();
        } else {
          c2GTest2ListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public Builder addC2GTest2List(
          int index, protocol.client.gate.C2G.C2GTest2.Builder builderForValue) {
        if (c2GTest2ListBuilder_ == null) {
          ensureC2GTest2ListIsMutable();
          c2GTest2List_.add(index, builderForValue.build());
          onChanged();
        } else {
          c2GTest2ListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public Builder addAllC2GTest2List(
          java.lang.Iterable<? extends protocol.client.gate.C2G.C2GTest2> values) {
        if (c2GTest2ListBuilder_ == null) {
          ensureC2GTest2ListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, c2GTest2List_);
          onChanged();
        } else {
          c2GTest2ListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public Builder clearC2GTest2List() {
        if (c2GTest2ListBuilder_ == null) {
          c2GTest2List_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          c2GTest2ListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public Builder removeC2GTest2List(int index) {
        if (c2GTest2ListBuilder_ == null) {
          ensureC2GTest2ListIsMutable();
          c2GTest2List_.remove(index);
          onChanged();
        } else {
          c2GTest2ListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public protocol.client.gate.C2G.C2GTest2.Builder getC2GTest2ListBuilder(
          int index) {
        return getC2GTest2ListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public protocol.client.gate.C2G.C2GTest2OrBuilder getC2GTest2ListOrBuilder(
          int index) {
        if (c2GTest2ListBuilder_ == null) {
          return c2GTest2List_.get(index);  } else {
          return c2GTest2ListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public java.util.List<? extends protocol.client.gate.C2G.C2GTest2OrBuilder> 
           getC2GTest2ListOrBuilderList() {
        if (c2GTest2ListBuilder_ != null) {
          return c2GTest2ListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(c2GTest2List_);
        }
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public protocol.client.gate.C2G.C2GTest2.Builder addC2GTest2ListBuilder() {
        return getC2GTest2ListFieldBuilder().addBuilder(
            protocol.client.gate.C2G.C2GTest2.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public protocol.client.gate.C2G.C2GTest2.Builder addC2GTest2ListBuilder(
          int index) {
        return getC2GTest2ListFieldBuilder().addBuilder(
            index, protocol.client.gate.C2G.C2GTest2.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.client.gate.C2GTest2 c2gTest2List = 3;</code>
       */
      public java.util.List<protocol.client.gate.C2G.C2GTest2.Builder> 
           getC2GTest2ListBuilderList() {
        return getC2GTest2ListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.client.gate.C2G.C2GTest2, protocol.client.gate.C2G.C2GTest2.Builder, protocol.client.gate.C2G.C2GTest2OrBuilder> 
          getC2GTest2ListFieldBuilder() {
        if (c2GTest2ListBuilder_ == null) {
          c2GTest2ListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.client.gate.C2G.C2GTest2, protocol.client.gate.C2G.C2GTest2.Builder, protocol.client.gate.C2G.C2GTest2OrBuilder>(
                  c2GTest2List_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          c2GTest2List_ = null;
        }
        return c2GTest2ListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.client.gate.C2GTest1)
    }

    // @@protoc_insertion_point(class_scope:protocol.client.gate.C2GTest1)
    private static final protocol.client.gate.C2G.C2GTest1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.client.gate.C2G.C2GTest1();
    }

    public static protocol.client.gate.C2G.C2GTest1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2GTest1>
        PARSER = new com.google.protobuf.AbstractParser<C2GTest1>() {
      public C2GTest1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2GTest1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2GTest1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2GTest1> getParserForType() {
      return PARSER;
    }

    public protocol.client.gate.C2G.C2GTest1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2GTest2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.client.gate.C2GTest2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 testint1 = 1;</code>
     */
    boolean hasTestint1();
    /**
     * <code>required int32 testint1 = 1;</code>
     */
    int getTestint1();

    /**
     * <code>required int32 testint2 = 2;</code>
     */
    boolean hasTestint2();
    /**
     * <code>required int32 testint2 = 2;</code>
     */
    int getTestint2();
  }
  /**
   * Protobuf type {@code protocol.client.gate.C2GTest2}
   */
  public  static final class C2GTest2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.client.gate.C2GTest2)
      C2GTest2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2GTest2.newBuilder() to construct.
    private C2GTest2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2GTest2() {
      testint1_ = 0;
      testint2_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2GTest2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              testint1_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              testint2_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.client.gate.C2G.C2GTest2.class, protocol.client.gate.C2G.C2GTest2.Builder.class);
    }

    private int bitField0_;
    public static final int TESTINT1_FIELD_NUMBER = 1;
    private int testint1_;
    /**
     * <code>required int32 testint1 = 1;</code>
     */
    public boolean hasTestint1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 testint1 = 1;</code>
     */
    public int getTestint1() {
      return testint1_;
    }

    public static final int TESTINT2_FIELD_NUMBER = 2;
    private int testint2_;
    /**
     * <code>required int32 testint2 = 2;</code>
     */
    public boolean hasTestint2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 testint2 = 2;</code>
     */
    public int getTestint2() {
      return testint2_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTestint1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTestint2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, testint1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, testint2_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, testint1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, testint2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.client.gate.C2G.C2GTest2)) {
        return super.equals(obj);
      }
      protocol.client.gate.C2G.C2GTest2 other = (protocol.client.gate.C2G.C2GTest2) obj;

      boolean result = true;
      result = result && (hasTestint1() == other.hasTestint1());
      if (hasTestint1()) {
        result = result && (getTestint1()
            == other.getTestint1());
      }
      result = result && (hasTestint2() == other.hasTestint2());
      if (hasTestint2()) {
        result = result && (getTestint2()
            == other.getTestint2());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestint1()) {
        hash = (37 * hash) + TESTINT1_FIELD_NUMBER;
        hash = (53 * hash) + getTestint1();
      }
      if (hasTestint2()) {
        hash = (37 * hash) + TESTINT2_FIELD_NUMBER;
        hash = (53 * hash) + getTestint2();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.client.gate.C2G.C2GTest2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.client.gate.C2G.C2GTest2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.client.gate.C2G.C2GTest2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.client.gate.C2GTest2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.client.gate.C2GTest2)
        protocol.client.gate.C2G.C2GTest2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.client.gate.C2G.C2GTest2.class, protocol.client.gate.C2G.C2GTest2.Builder.class);
      }

      // Construct using protocol.client.gate.C2G.C2GTest2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        testint1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        testint2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest2_descriptor;
      }

      public protocol.client.gate.C2G.C2GTest2 getDefaultInstanceForType() {
        return protocol.client.gate.C2G.C2GTest2.getDefaultInstance();
      }

      public protocol.client.gate.C2G.C2GTest2 build() {
        protocol.client.gate.C2G.C2GTest2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.client.gate.C2G.C2GTest2 buildPartial() {
        protocol.client.gate.C2G.C2GTest2 result = new protocol.client.gate.C2G.C2GTest2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testint1_ = testint1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.testint2_ = testint2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.client.gate.C2G.C2GTest2) {
          return mergeFrom((protocol.client.gate.C2G.C2GTest2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.client.gate.C2G.C2GTest2 other) {
        if (other == protocol.client.gate.C2G.C2GTest2.getDefaultInstance()) return this;
        if (other.hasTestint1()) {
          setTestint1(other.getTestint1());
        }
        if (other.hasTestint2()) {
          setTestint2(other.getTestint2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestint1()) {
          return false;
        }
        if (!hasTestint2()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.client.gate.C2G.C2GTest2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.client.gate.C2G.C2GTest2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int testint1_ ;
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public boolean hasTestint1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public int getTestint1() {
        return testint1_;
      }
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public Builder setTestint1(int value) {
        bitField0_ |= 0x00000001;
        testint1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public Builder clearTestint1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testint1_ = 0;
        onChanged();
        return this;
      }

      private int testint2_ ;
      /**
       * <code>required int32 testint2 = 2;</code>
       */
      public boolean hasTestint2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 testint2 = 2;</code>
       */
      public int getTestint2() {
        return testint2_;
      }
      /**
       * <code>required int32 testint2 = 2;</code>
       */
      public Builder setTestint2(int value) {
        bitField0_ |= 0x00000002;
        testint2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 testint2 = 2;</code>
       */
      public Builder clearTestint2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        testint2_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.client.gate.C2GTest2)
    }

    // @@protoc_insertion_point(class_scope:protocol.client.gate.C2GTest2)
    private static final protocol.client.gate.C2G.C2GTest2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.client.gate.C2G.C2GTest2();
    }

    public static protocol.client.gate.C2G.C2GTest2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2GTest2>
        PARSER = new com.google.protobuf.AbstractParser<C2GTest2>() {
      public C2GTest2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2GTest2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2GTest2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2GTest2> getParserForType() {
      return PARSER;
    }

    public protocol.client.gate.C2G.C2GTest2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2GTest3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.client.gate.C2GTest3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 testint3 = 1;</code>
     */
    boolean hasTestint3();
    /**
     * <code>required int32 testint3 = 1;</code>
     */
    int getTestint3();

    /**
     * <code>required string teststring3 = 2;</code>
     */
    boolean hasTeststring3();
    /**
     * <code>required string teststring3 = 2;</code>
     */
    java.lang.String getTeststring3();
    /**
     * <code>required string teststring3 = 2;</code>
     */
    com.google.protobuf.ByteString
        getTeststring3Bytes();
  }
  /**
   * Protobuf type {@code protocol.client.gate.C2GTest3}
   */
  public  static final class C2GTest3 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.client.gate.C2GTest3)
      C2GTest3OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2GTest3.newBuilder() to construct.
    private C2GTest3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2GTest3() {
      testint3_ = 0;
      teststring3_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2GTest3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              testint3_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              teststring3_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest3_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.client.gate.C2G.C2GTest3.class, protocol.client.gate.C2G.C2GTest3.Builder.class);
    }

    private int bitField0_;
    public static final int TESTINT3_FIELD_NUMBER = 1;
    private int testint3_;
    /**
     * <code>required int32 testint3 = 1;</code>
     */
    public boolean hasTestint3() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 testint3 = 1;</code>
     */
    public int getTestint3() {
      return testint3_;
    }

    public static final int TESTSTRING3_FIELD_NUMBER = 2;
    private volatile java.lang.Object teststring3_;
    /**
     * <code>required string teststring3 = 2;</code>
     */
    public boolean hasTeststring3() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string teststring3 = 2;</code>
     */
    public java.lang.String getTeststring3() {
      java.lang.Object ref = teststring3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teststring3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string teststring3 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTeststring3Bytes() {
      java.lang.Object ref = teststring3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teststring3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTestint3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeststring3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, testint3_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, teststring3_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, testint3_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, teststring3_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.client.gate.C2G.C2GTest3)) {
        return super.equals(obj);
      }
      protocol.client.gate.C2G.C2GTest3 other = (protocol.client.gate.C2G.C2GTest3) obj;

      boolean result = true;
      result = result && (hasTestint3() == other.hasTestint3());
      if (hasTestint3()) {
        result = result && (getTestint3()
            == other.getTestint3());
      }
      result = result && (hasTeststring3() == other.hasTeststring3());
      if (hasTeststring3()) {
        result = result && getTeststring3()
            .equals(other.getTeststring3());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestint3()) {
        hash = (37 * hash) + TESTINT3_FIELD_NUMBER;
        hash = (53 * hash) + getTestint3();
      }
      if (hasTeststring3()) {
        hash = (37 * hash) + TESTSTRING3_FIELD_NUMBER;
        hash = (53 * hash) + getTeststring3().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.client.gate.C2G.C2GTest3 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.client.gate.C2G.C2GTest3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.client.gate.C2G.C2GTest3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.client.gate.C2GTest3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.client.gate.C2GTest3)
        protocol.client.gate.C2G.C2GTest3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest3_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.client.gate.C2G.C2GTest3.class, protocol.client.gate.C2G.C2GTest3.Builder.class);
      }

      // Construct using protocol.client.gate.C2G.C2GTest3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        testint3_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        teststring3_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.client.gate.C2G.internal_static_protocol_client_gate_C2GTest3_descriptor;
      }

      public protocol.client.gate.C2G.C2GTest3 getDefaultInstanceForType() {
        return protocol.client.gate.C2G.C2GTest3.getDefaultInstance();
      }

      public protocol.client.gate.C2G.C2GTest3 build() {
        protocol.client.gate.C2G.C2GTest3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.client.gate.C2G.C2GTest3 buildPartial() {
        protocol.client.gate.C2G.C2GTest3 result = new protocol.client.gate.C2G.C2GTest3(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testint3_ = testint3_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teststring3_ = teststring3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.client.gate.C2G.C2GTest3) {
          return mergeFrom((protocol.client.gate.C2G.C2GTest3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.client.gate.C2G.C2GTest3 other) {
        if (other == protocol.client.gate.C2G.C2GTest3.getDefaultInstance()) return this;
        if (other.hasTestint3()) {
          setTestint3(other.getTestint3());
        }
        if (other.hasTeststring3()) {
          bitField0_ |= 0x00000002;
          teststring3_ = other.teststring3_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestint3()) {
          return false;
        }
        if (!hasTeststring3()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.client.gate.C2G.C2GTest3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.client.gate.C2G.C2GTest3) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int testint3_ ;
      /**
       * <code>required int32 testint3 = 1;</code>
       */
      public boolean hasTestint3() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 testint3 = 1;</code>
       */
      public int getTestint3() {
        return testint3_;
      }
      /**
       * <code>required int32 testint3 = 1;</code>
       */
      public Builder setTestint3(int value) {
        bitField0_ |= 0x00000001;
        testint3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 testint3 = 1;</code>
       */
      public Builder clearTestint3() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testint3_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object teststring3_ = "";
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public boolean hasTeststring3() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public java.lang.String getTeststring3() {
        java.lang.Object ref = teststring3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            teststring3_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTeststring3Bytes() {
        java.lang.Object ref = teststring3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teststring3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public Builder setTeststring3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public Builder clearTeststring3() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teststring3_ = getDefaultInstance().getTeststring3();
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public Builder setTeststring3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring3_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.client.gate.C2GTest3)
    }

    // @@protoc_insertion_point(class_scope:protocol.client.gate.C2GTest3)
    private static final protocol.client.gate.C2G.C2GTest3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.client.gate.C2G.C2GTest3();
    }

    public static protocol.client.gate.C2G.C2GTest3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2GTest3>
        PARSER = new com.google.protobuf.AbstractParser<C2GTest3>() {
      public C2GTest3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2GTest3(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2GTest3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2GTest3> getParserForType() {
      return PARSER;
    }

    public protocol.client.gate.C2G.C2GTest3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_client_gate_C2GTest1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_client_gate_C2GTest1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_client_gate_C2GTest2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_client_gate_C2GTest2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_client_gate_C2GTest3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_client_gate_C2GTest3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tC2G.proto\022\024protocol.client.gate\"g\n\010C2G" +
      "Test1\022\020\n\010testint1\030\001 \002(\005\022\023\n\013teststring1\030\002" +
      " \002(\t\0224\n\014c2gTest2List\030\003 \003(\0132\036.protocol.cl" +
      "ient.gate.C2GTest2\".\n\010C2GTest2\022\020\n\010testin" +
      "t1\030\001 \002(\005\022\020\n\010testint2\030\002 \002(\005\"1\n\010C2GTest3\022\020" +
      "\n\010testint3\030\001 \002(\005\022\023\n\013teststring3\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_client_gate_C2GTest1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_client_gate_C2GTest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_client_gate_C2GTest1_descriptor,
        new java.lang.String[] { "Testint1", "Teststring1", "C2GTest2List", });
    internal_static_protocol_client_gate_C2GTest2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_client_gate_C2GTest2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_client_gate_C2GTest2_descriptor,
        new java.lang.String[] { "Testint1", "Testint2", });
    internal_static_protocol_client_gate_C2GTest3_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_client_gate_C2GTest3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_client_gate_C2GTest3_descriptor,
        new java.lang.String[] { "Testint3", "Teststring3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
