//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Protocol/Gate/G2GM.proto
namespace protocol.gate.global
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_G2GM_HEARTBEAT")]
  public partial class MSG_G2GM_HEARTBEAT : global::ProtoBuf.IExtensible
  {
    public MSG_G2GM_HEARTBEAT() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}