 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.client.server;
import protocol.msgId.Id;
public class C2SIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(protocol.client.server.C2S.GOODS_INFO.class, 0x1200001);
          Id.getInst().SetMessage(protocol.client.server.C2S.GOODS_INFO_ARRAY.class, 0x1200002);
          Id.getInst().SetMessage(protocol.client.server.C2S.C2GTest3.class, 0x1200003);
     }
}
