// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

package protocol.client.server;

public final class Enum {
  private Enum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protocol.client.server.EnmCmdID}
   */
  public enum EnmCmdID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CS_LOGIN_REQ = 10001;</code>
     */
    CS_LOGIN_REQ(10001),
    /**
     * <code>CS_LOGIN_RES = 10002;</code>
     */
    CS_LOGIN_RES(10002),
    ;

    /**
     * <code>CS_LOGIN_REQ = 10001;</code>
     */
    public static final int CS_LOGIN_REQ_VALUE = 10001;
    /**
     * <code>CS_LOGIN_RES = 10002;</code>
     */
    public static final int CS_LOGIN_RES_VALUE = 10002;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnmCmdID valueOf(int value) {
      return forNumber(value);
    }

    public static EnmCmdID forNumber(int value) {
      switch (value) {
        case 10001: return CS_LOGIN_REQ;
        case 10002: return CS_LOGIN_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnmCmdID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnmCmdID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnmCmdID>() {
            public EnmCmdID findValueByNumber(int number) {
              return EnmCmdID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.client.server.Enum.getDescriptor().getEnumTypes().get(0);
    }

    private static final EnmCmdID[] VALUES = values();

    public static EnmCmdID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnmCmdID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.client.server.EnmCmdID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nEnum.proto\022\026protocol.client.server*0\n\010" +
      "EnmCmdID\022\021\n\014CS_LOGIN_REQ\020\221N\022\021\n\014CS_LOGIN_" +
      "RES\020\222N"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
