//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ServerRegister.proto
namespace protocol.server.register
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_REQ_Server_Register")]
  public partial class MSG_REQ_Server_Register : global::ProtoBuf.IExtensible
  {
    public MSG_REQ_Server_Register() {}
    
    private int _serverType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serverType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverType
    {
      get { return _serverType; }
      set { _serverType = value; }
    }

    private int _groupId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }

    private int _subId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"subId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int subId
    {
      get { return _subId; }
      set { _subId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_RES_Server_Register")]
  public partial class MSG_RES_Server_Register : global::ProtoBuf.IExtensible
  {
    public MSG_RES_Server_Register() {}
    
    private int _serverType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serverType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverType
    {
      get { return _serverType; }
      set { _serverType = value; }
    }

    private int _groupId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }

    private int _subId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"subId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int subId
    {
      get { return _subId; }
      set { _subId = value; }
    }
    private uint _result;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectInfo")]
  public partial class ConnectInfo : global::ProtoBuf.IExtensible
  {
    public ConnectInfo() {}
    
    private int _port;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}