/************************************************************************ 
 * 项目名称 :  ProtocolGenerator.Core.Java       
 * 类 名 称 :  JavaCodeGenerator 
 * 类 描 述 : 
 * 版 本 号 :  v1.0.0.0  
 * 说    明 :      
 * 作    者 :  FReedom 
 * 创建时间 :  2018/4/21 星期六 11:32:14 
 * 更新时间 :  2018/4/21 星期六 11:32:14 
************************************************************************ 
 * Copyright @ BoilingBlood 2018. All rights reserved. 
************************************************************************/
using System;
using System.Collections.Generic;
using System.Text;

namespace ProtocolGenerator.Core.Java
{
    public class JavaCodeGenerator : ICodeGenerator
    {
        string spaceStr = "     ";
        private string SetSpace(int spaceCount)
        {
            StringBuilder space = new StringBuilder();
            for (int i = 0; i < spaceCount; i++)
            {
                space.Append(spaceStr);
            }
            return space.ToString();
        }
        public StringBuilder ClassCommentsFrame()
        {
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.(The author is Boiling)
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.  
            // </auto-generated>
            //------------------------------------------------------------------------------

            StringBuilder sb = new StringBuilder();
            sb.Append(" //------------------------------------------------------------------------------");
            sb.Append(Environment.NewLine);
            sb.Append(" // <auto-generated>");
            sb.Append(Environment.NewLine);
            sb.Append(" //     This code was generated by a tool.(The author is Boiling)");
            sb.Append(Environment.NewLine);
            sb.Append(" //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
            sb.Append(Environment.NewLine);
            sb.Append(" // </auto-generated>");
            sb.Append(Environment.NewLine);
            sb.Append(" //------------------------------------------------------------------------------");
            sb.Append(Environment.NewLine);
            return sb;
        }

        public StringBuilder IncludeHeadFrame( List<string> imports)
        {
            StringBuilder sb = new StringBuilder();
            foreach (var item in imports)
            {
                sb.Append(item);
                sb.Append(Environment.NewLine);
            }
            return sb;
        }


        public StringBuilder AttrFrame(string attrType, string attrName, int spaceCount = 2)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append(SetSpace(spaceCount));
            sb.Append(attrType);
            sb.Append(" ");
            sb.Append(attrName);
            sb.Append(";");
            sb.Append(Environment.NewLine);
            return sb;
        }

        public StringBuilder ClassFrame(string className, List<StringBuilder> attrs = null, List<StringBuilder> methods = null, int spaceCount = 1)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append(SetSpace(spaceCount));
            sb.Append("public ");
            sb.Append(className);
            sb.Append("{");
            sb.Append(Environment.NewLine);
            if (attrs != null)
            {
                foreach (var item in attrs)
                {
                    sb.Append(item.ToString());
                }
            }
            if (methods != null)
            {
                foreach (var item in methods)
                {
                    sb.Append(item.ToString());
                }
            }
            sb.Append(SetSpace(spaceCount));
            sb.Append("}");
            return sb;
        }

        public StringBuilder MethodFrame(string methodType, string methodName, List<StringBuilder> methodValue, int spaceCount = 2)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append(SetSpace(spaceCount));
            sb.Append("public ");
            sb.Append(methodType);
            sb.Append(" ");
            sb.Append(methodName);
            sb.Append("{");
            sb.Append(Environment.NewLine);
            foreach (var item in methodValue)
            {
                sb.Append(SetSpace(1));
                sb.Append(item.ToString());
            }
            sb.Append(SetSpace(spaceCount));
            sb.Append("}");
            sb.Append(Environment.NewLine);
            return sb;
        }

        public StringBuilder NameSpaceFrame(string nameSpace, StringBuilder classBody)
        {
            return null;
        }
    }
}
