 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package Message.Server.Register;
import message.idgenerator.Id;
public class ServerRegisterIdGenerator{
     public static void GenerateId(){
          Id.getInst().SetMessage(Message.Server.Register.ServerRegister.MSG_Server_Register.class, 0xff0001);
          Id.getInst().SetMessage(Message.Server.Register.ServerRegister.MSG_Server_Register_Return.class, 0xff0002);
          Id.getInst().SetMessage(Message.Server.Register.ServerRegister.MSG_Server_Connect_Command.class, 0xff0004);
     }
}
