// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: G2C.proto

package protocol.gate.client;

public final class G2C {
  private G2C() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface G2CTest1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.gate.client.G2CTest1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 testint1 = 1;</code>
     */
    boolean hasTestint1();
    /**
     * <code>required int32 testint1 = 1;</code>
     */
    int getTestint1();

    /**
     * <code>required string teststring1 = 2;</code>
     */
    boolean hasTeststring1();
    /**
     * <code>required string teststring1 = 2;</code>
     */
    java.lang.String getTeststring1();
    /**
     * <code>required string teststring1 = 2;</code>
     */
    com.google.protobuf.ByteString
        getTeststring1Bytes();
  }
  /**
   * Protobuf type {@code protocol.gate.client.G2CTest1}
   */
  public  static final class G2CTest1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.gate.client.G2CTest1)
      G2CTest1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use G2CTest1.newBuilder() to construct.
    private G2CTest1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private G2CTest1() {
      testint1_ = 0;
      teststring1_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private G2CTest1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              testint1_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              teststring1_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.gate.client.G2C.G2CTest1.class, protocol.gate.client.G2C.G2CTest1.Builder.class);
    }

    private int bitField0_;
    public static final int TESTINT1_FIELD_NUMBER = 1;
    private int testint1_;
    /**
     * <code>required int32 testint1 = 1;</code>
     */
    public boolean hasTestint1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 testint1 = 1;</code>
     */
    public int getTestint1() {
      return testint1_;
    }

    public static final int TESTSTRING1_FIELD_NUMBER = 2;
    private volatile java.lang.Object teststring1_;
    /**
     * <code>required string teststring1 = 2;</code>
     */
    public boolean hasTeststring1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string teststring1 = 2;</code>
     */
    public java.lang.String getTeststring1() {
      java.lang.Object ref = teststring1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teststring1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string teststring1 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTeststring1Bytes() {
      java.lang.Object ref = teststring1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teststring1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTestint1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeststring1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, testint1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, teststring1_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, testint1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, teststring1_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.gate.client.G2C.G2CTest1)) {
        return super.equals(obj);
      }
      protocol.gate.client.G2C.G2CTest1 other = (protocol.gate.client.G2C.G2CTest1) obj;

      boolean result = true;
      result = result && (hasTestint1() == other.hasTestint1());
      if (hasTestint1()) {
        result = result && (getTestint1()
            == other.getTestint1());
      }
      result = result && (hasTeststring1() == other.hasTeststring1());
      if (hasTeststring1()) {
        result = result && getTeststring1()
            .equals(other.getTeststring1());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestint1()) {
        hash = (37 * hash) + TESTINT1_FIELD_NUMBER;
        hash = (53 * hash) + getTestint1();
      }
      if (hasTeststring1()) {
        hash = (37 * hash) + TESTSTRING1_FIELD_NUMBER;
        hash = (53 * hash) + getTeststring1().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.gate.client.G2C.G2CTest1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.gate.client.G2C.G2CTest1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.gate.client.G2C.G2CTest1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.gate.client.G2CTest1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.gate.client.G2CTest1)
        protocol.gate.client.G2C.G2CTest1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.gate.client.G2C.G2CTest1.class, protocol.gate.client.G2C.G2CTest1.Builder.class);
      }

      // Construct using protocol.gate.client.G2C.G2CTest1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        testint1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        teststring1_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest1_descriptor;
      }

      public protocol.gate.client.G2C.G2CTest1 getDefaultInstanceForType() {
        return protocol.gate.client.G2C.G2CTest1.getDefaultInstance();
      }

      public protocol.gate.client.G2C.G2CTest1 build() {
        protocol.gate.client.G2C.G2CTest1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.gate.client.G2C.G2CTest1 buildPartial() {
        protocol.gate.client.G2C.G2CTest1 result = new protocol.gate.client.G2C.G2CTest1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testint1_ = testint1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teststring1_ = teststring1_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.gate.client.G2C.G2CTest1) {
          return mergeFrom((protocol.gate.client.G2C.G2CTest1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.gate.client.G2C.G2CTest1 other) {
        if (other == protocol.gate.client.G2C.G2CTest1.getDefaultInstance()) return this;
        if (other.hasTestint1()) {
          setTestint1(other.getTestint1());
        }
        if (other.hasTeststring1()) {
          bitField0_ |= 0x00000002;
          teststring1_ = other.teststring1_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestint1()) {
          return false;
        }
        if (!hasTeststring1()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.gate.client.G2C.G2CTest1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.gate.client.G2C.G2CTest1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int testint1_ ;
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public boolean hasTestint1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public int getTestint1() {
        return testint1_;
      }
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public Builder setTestint1(int value) {
        bitField0_ |= 0x00000001;
        testint1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 testint1 = 1;</code>
       */
      public Builder clearTestint1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testint1_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object teststring1_ = "";
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public boolean hasTeststring1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public java.lang.String getTeststring1() {
        java.lang.Object ref = teststring1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            teststring1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTeststring1Bytes() {
        java.lang.Object ref = teststring1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teststring1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public Builder setTeststring1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public Builder clearTeststring1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teststring1_ = getDefaultInstance().getTeststring1();
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring1 = 2;</code>
       */
      public Builder setTeststring1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring1_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.gate.client.G2CTest1)
    }

    // @@protoc_insertion_point(class_scope:protocol.gate.client.G2CTest1)
    private static final protocol.gate.client.G2C.G2CTest1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.gate.client.G2C.G2CTest1();
    }

    public static protocol.gate.client.G2C.G2CTest1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<G2CTest1>
        PARSER = new com.google.protobuf.AbstractParser<G2CTest1>() {
      public G2CTest1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new G2CTest1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<G2CTest1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<G2CTest1> getParserForType() {
      return PARSER;
    }

    public protocol.gate.client.G2C.G2CTest1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface G2CTest2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.gate.client.G2CTest2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 testint2 = 1;</code>
     */
    boolean hasTestint2();
    /**
     * <code>required int32 testint2 = 1;</code>
     */
    int getTestint2();

    /**
     * <code>required string teststring2 = 2;</code>
     */
    boolean hasTeststring2();
    /**
     * <code>required string teststring2 = 2;</code>
     */
    java.lang.String getTeststring2();
    /**
     * <code>required string teststring2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getTeststring2Bytes();
  }
  /**
   * Protobuf type {@code protocol.gate.client.G2CTest2}
   */
  public  static final class G2CTest2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.gate.client.G2CTest2)
      G2CTest2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use G2CTest2.newBuilder() to construct.
    private G2CTest2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private G2CTest2() {
      testint2_ = 0;
      teststring2_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private G2CTest2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              testint2_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              teststring2_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.gate.client.G2C.G2CTest2.class, protocol.gate.client.G2C.G2CTest2.Builder.class);
    }

    private int bitField0_;
    public static final int TESTINT2_FIELD_NUMBER = 1;
    private int testint2_;
    /**
     * <code>required int32 testint2 = 1;</code>
     */
    public boolean hasTestint2() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 testint2 = 1;</code>
     */
    public int getTestint2() {
      return testint2_;
    }

    public static final int TESTSTRING2_FIELD_NUMBER = 2;
    private volatile java.lang.Object teststring2_;
    /**
     * <code>required string teststring2 = 2;</code>
     */
    public boolean hasTeststring2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string teststring2 = 2;</code>
     */
    public java.lang.String getTeststring2() {
      java.lang.Object ref = teststring2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teststring2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string teststring2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTeststring2Bytes() {
      java.lang.Object ref = teststring2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teststring2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTestint2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeststring2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, testint2_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, teststring2_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, testint2_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, teststring2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.gate.client.G2C.G2CTest2)) {
        return super.equals(obj);
      }
      protocol.gate.client.G2C.G2CTest2 other = (protocol.gate.client.G2C.G2CTest2) obj;

      boolean result = true;
      result = result && (hasTestint2() == other.hasTestint2());
      if (hasTestint2()) {
        result = result && (getTestint2()
            == other.getTestint2());
      }
      result = result && (hasTeststring2() == other.hasTeststring2());
      if (hasTeststring2()) {
        result = result && getTeststring2()
            .equals(other.getTeststring2());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestint2()) {
        hash = (37 * hash) + TESTINT2_FIELD_NUMBER;
        hash = (53 * hash) + getTestint2();
      }
      if (hasTeststring2()) {
        hash = (37 * hash) + TESTSTRING2_FIELD_NUMBER;
        hash = (53 * hash) + getTeststring2().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.gate.client.G2C.G2CTest2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.gate.client.G2C.G2CTest2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.gate.client.G2C.G2CTest2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.gate.client.G2CTest2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.gate.client.G2CTest2)
        protocol.gate.client.G2C.G2CTest2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.gate.client.G2C.G2CTest2.class, protocol.gate.client.G2C.G2CTest2.Builder.class);
      }

      // Construct using protocol.gate.client.G2C.G2CTest2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        testint2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        teststring2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest2_descriptor;
      }

      public protocol.gate.client.G2C.G2CTest2 getDefaultInstanceForType() {
        return protocol.gate.client.G2C.G2CTest2.getDefaultInstance();
      }

      public protocol.gate.client.G2C.G2CTest2 build() {
        protocol.gate.client.G2C.G2CTest2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.gate.client.G2C.G2CTest2 buildPartial() {
        protocol.gate.client.G2C.G2CTest2 result = new protocol.gate.client.G2C.G2CTest2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testint2_ = testint2_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teststring2_ = teststring2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.gate.client.G2C.G2CTest2) {
          return mergeFrom((protocol.gate.client.G2C.G2CTest2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.gate.client.G2C.G2CTest2 other) {
        if (other == protocol.gate.client.G2C.G2CTest2.getDefaultInstance()) return this;
        if (other.hasTestint2()) {
          setTestint2(other.getTestint2());
        }
        if (other.hasTeststring2()) {
          bitField0_ |= 0x00000002;
          teststring2_ = other.teststring2_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestint2()) {
          return false;
        }
        if (!hasTeststring2()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.gate.client.G2C.G2CTest2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.gate.client.G2C.G2CTest2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int testint2_ ;
      /**
       * <code>required int32 testint2 = 1;</code>
       */
      public boolean hasTestint2() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 testint2 = 1;</code>
       */
      public int getTestint2() {
        return testint2_;
      }
      /**
       * <code>required int32 testint2 = 1;</code>
       */
      public Builder setTestint2(int value) {
        bitField0_ |= 0x00000001;
        testint2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 testint2 = 1;</code>
       */
      public Builder clearTestint2() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testint2_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object teststring2_ = "";
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public boolean hasTeststring2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public java.lang.String getTeststring2() {
        java.lang.Object ref = teststring2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            teststring2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTeststring2Bytes() {
        java.lang.Object ref = teststring2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teststring2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public Builder setTeststring2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public Builder clearTeststring2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teststring2_ = getDefaultInstance().getTeststring2();
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring2 = 2;</code>
       */
      public Builder setTeststring2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring2_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.gate.client.G2CTest2)
    }

    // @@protoc_insertion_point(class_scope:protocol.gate.client.G2CTest2)
    private static final protocol.gate.client.G2C.G2CTest2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.gate.client.G2C.G2CTest2();
    }

    public static protocol.gate.client.G2C.G2CTest2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<G2CTest2>
        PARSER = new com.google.protobuf.AbstractParser<G2CTest2>() {
      public G2CTest2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new G2CTest2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<G2CTest2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<G2CTest2> getParserForType() {
      return PARSER;
    }

    public protocol.gate.client.G2C.G2CTest2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface G2CTest3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.gate.client.G2CTest3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 testint3 = 1;</code>
     */
    boolean hasTestint3();
    /**
     * <code>required int32 testint3 = 1;</code>
     */
    int getTestint3();

    /**
     * <code>required string teststring3 = 2;</code>
     */
    boolean hasTeststring3();
    /**
     * <code>required string teststring3 = 2;</code>
     */
    java.lang.String getTeststring3();
    /**
     * <code>required string teststring3 = 2;</code>
     */
    com.google.protobuf.ByteString
        getTeststring3Bytes();
  }
  /**
   * Protobuf type {@code protocol.gate.client.G2CTest3}
   */
  public  static final class G2CTest3 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.gate.client.G2CTest3)
      G2CTest3OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use G2CTest3.newBuilder() to construct.
    private G2CTest3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private G2CTest3() {
      testint3_ = 0;
      teststring3_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private G2CTest3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              testint3_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              teststring3_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest3_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.gate.client.G2C.G2CTest3.class, protocol.gate.client.G2C.G2CTest3.Builder.class);
    }

    private int bitField0_;
    public static final int TESTINT3_FIELD_NUMBER = 1;
    private int testint3_;
    /**
     * <code>required int32 testint3 = 1;</code>
     */
    public boolean hasTestint3() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 testint3 = 1;</code>
     */
    public int getTestint3() {
      return testint3_;
    }

    public static final int TESTSTRING3_FIELD_NUMBER = 2;
    private volatile java.lang.Object teststring3_;
    /**
     * <code>required string teststring3 = 2;</code>
     */
    public boolean hasTeststring3() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string teststring3 = 2;</code>
     */
    public java.lang.String getTeststring3() {
      java.lang.Object ref = teststring3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teststring3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string teststring3 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTeststring3Bytes() {
      java.lang.Object ref = teststring3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teststring3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTestint3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeststring3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, testint3_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, teststring3_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, testint3_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, teststring3_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.gate.client.G2C.G2CTest3)) {
        return super.equals(obj);
      }
      protocol.gate.client.G2C.G2CTest3 other = (protocol.gate.client.G2C.G2CTest3) obj;

      boolean result = true;
      result = result && (hasTestint3() == other.hasTestint3());
      if (hasTestint3()) {
        result = result && (getTestint3()
            == other.getTestint3());
      }
      result = result && (hasTeststring3() == other.hasTeststring3());
      if (hasTeststring3()) {
        result = result && getTeststring3()
            .equals(other.getTeststring3());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestint3()) {
        hash = (37 * hash) + TESTINT3_FIELD_NUMBER;
        hash = (53 * hash) + getTestint3();
      }
      if (hasTeststring3()) {
        hash = (37 * hash) + TESTSTRING3_FIELD_NUMBER;
        hash = (53 * hash) + getTeststring3().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.gate.client.G2C.G2CTest3 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.gate.client.G2C.G2CTest3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.gate.client.G2C.G2CTest3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.gate.client.G2CTest3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.gate.client.G2CTest3)
        protocol.gate.client.G2C.G2CTest3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest3_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.gate.client.G2C.G2CTest3.class, protocol.gate.client.G2C.G2CTest3.Builder.class);
      }

      // Construct using protocol.gate.client.G2C.G2CTest3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        testint3_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        teststring3_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.gate.client.G2C.internal_static_protocol_gate_client_G2CTest3_descriptor;
      }

      public protocol.gate.client.G2C.G2CTest3 getDefaultInstanceForType() {
        return protocol.gate.client.G2C.G2CTest3.getDefaultInstance();
      }

      public protocol.gate.client.G2C.G2CTest3 build() {
        protocol.gate.client.G2C.G2CTest3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.gate.client.G2C.G2CTest3 buildPartial() {
        protocol.gate.client.G2C.G2CTest3 result = new protocol.gate.client.G2C.G2CTest3(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testint3_ = testint3_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teststring3_ = teststring3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.gate.client.G2C.G2CTest3) {
          return mergeFrom((protocol.gate.client.G2C.G2CTest3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.gate.client.G2C.G2CTest3 other) {
        if (other == protocol.gate.client.G2C.G2CTest3.getDefaultInstance()) return this;
        if (other.hasTestint3()) {
          setTestint3(other.getTestint3());
        }
        if (other.hasTeststring3()) {
          bitField0_ |= 0x00000002;
          teststring3_ = other.teststring3_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestint3()) {
          return false;
        }
        if (!hasTeststring3()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.gate.client.G2C.G2CTest3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.gate.client.G2C.G2CTest3) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int testint3_ ;
      /**
       * <code>required int32 testint3 = 1;</code>
       */
      public boolean hasTestint3() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 testint3 = 1;</code>
       */
      public int getTestint3() {
        return testint3_;
      }
      /**
       * <code>required int32 testint3 = 1;</code>
       */
      public Builder setTestint3(int value) {
        bitField0_ |= 0x00000001;
        testint3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 testint3 = 1;</code>
       */
      public Builder clearTestint3() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testint3_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object teststring3_ = "";
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public boolean hasTeststring3() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public java.lang.String getTeststring3() {
        java.lang.Object ref = teststring3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            teststring3_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTeststring3Bytes() {
        java.lang.Object ref = teststring3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teststring3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public Builder setTeststring3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public Builder clearTeststring3() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teststring3_ = getDefaultInstance().getTeststring3();
        onChanged();
        return this;
      }
      /**
       * <code>required string teststring3 = 2;</code>
       */
      public Builder setTeststring3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teststring3_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.gate.client.G2CTest3)
    }

    // @@protoc_insertion_point(class_scope:protocol.gate.client.G2CTest3)
    private static final protocol.gate.client.G2C.G2CTest3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.gate.client.G2C.G2CTest3();
    }

    public static protocol.gate.client.G2C.G2CTest3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<G2CTest3>
        PARSER = new com.google.protobuf.AbstractParser<G2CTest3>() {
      public G2CTest3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new G2CTest3(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<G2CTest3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<G2CTest3> getParserForType() {
      return PARSER;
    }

    public protocol.gate.client.G2C.G2CTest3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_gate_client_G2CTest1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_gate_client_G2CTest1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_gate_client_G2CTest2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_gate_client_G2CTest2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_gate_client_G2CTest3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_gate_client_G2CTest3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tG2C.proto\022\024protocol.gate.client\"1\n\010G2C" +
      "Test1\022\020\n\010testint1\030\001 \002(\005\022\023\n\013teststring1\030\002" +
      " \002(\t\"1\n\010G2CTest2\022\020\n\010testint2\030\001 \002(\005\022\023\n\013te" +
      "ststring2\030\002 \002(\t\"1\n\010G2CTest3\022\020\n\010testint3\030" +
      "\001 \002(\005\022\023\n\013teststring3\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_gate_client_G2CTest1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_gate_client_G2CTest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_gate_client_G2CTest1_descriptor,
        new java.lang.String[] { "Testint1", "Teststring1", });
    internal_static_protocol_gate_client_G2CTest2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_gate_client_G2CTest2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_gate_client_G2CTest2_descriptor,
        new java.lang.String[] { "Testint2", "Teststring2", });
    internal_static_protocol_gate_client_G2CTest3_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_gate_client_G2CTest3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_gate_client_G2CTest3_descriptor,
        new java.lang.String[] { "Testint3", "Teststring3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
