 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.gate.client;
import protocol.msgId.Id;
public class G2CIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(protocol.gate.client.G2C.G2CTest1.class, 0x2100001);
          Id.getInst().SetMessage(protocol.gate.client.G2C.G2CTest2.class, 0x2100002);
          Id.getInst().SetMessage(protocol.gate.client.G2C.G2CTest3.class, 0x2100003);
     }
}
