 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
namespace protocol.client.server
{
     public class IdGenerater
     {
          public static void GenerateId()
          {
               Protocol.MsgId.Id<GOODS_INFO>.Value= 0x1200001;
               Protocol.MsgId.Id<GOODS_INFO_ARRAY>.Value= 0x1200002;
               Protocol.MsgId.Id<C2GTest3>.Value= 0x1200003;
          }
     }
}
