 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
namespace protocol.client.server
{
     public class IdGenerater
     {
          public static void GenerateId()
          {
               Protocol.MsgId.Id<MSG_GM2G_REQ_Register>.Value= 0x210001;
          }
     }
}
