// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: G2C.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Protocol.Gate.Client
{

    [global::ProtoBuf.ProtoContract()]
    public partial class G2CTest1 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"testint1", IsRequired = true)]
        public int Testint1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"teststring1", IsRequired = true)]
        public string Teststring1 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class G2CTest2 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"testint2", IsRequired = true)]
        public int Testint2 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"teststring2", IsRequired = true)]
        public string Teststring2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class G2CTest3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"testint3", IsRequired = true)]
        public int Testint3 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"teststring3", IsRequired = true)]
        public string Teststring3 { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
