 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
namespace Protocol.Gate.Client
{
     public class IdGenerater
     {
          public static void GenerateId()
          {
               Protocol.MsgId.Id<G2CTest1>.Value= 0x2100001;
               Protocol.MsgId.Id<G2CTest2>.Value= 0x2100002;
               Protocol.MsgId.Id<G2CTest3>.Value= 0x2100003;
          }
     }
}
