 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
namespace protocol.gate.global
{
     public class IdGenerater
     {
          public static void GenerateId()
          {
               Protocol.MsgId.Id<MSG_G2GM_HEARTBEAT>.Value= 0x210001;
               Protocol.MsgId.Id<MSG_G2GM_REQ_Register>.Value= 0x210002;
          }
     }
}
